### ISSUE TITLE
Netlify forms PLZ!

### ISSUE THREAD

**Issue by spences10** [spences10/scottspence.me#596]
Burned a day last weekend trying to use Netlify forms as a contact form on `src/pages/contact.js`

Using the simple example given on the Netlify site works but you can't wrap the page in a layout `src/components/layout.js` as it stops working as soon as you try that, so it works fine as a basic form but looks basic .af 

@sw-yx 

Tweet for context: https://twitter.com/ScottDevTweets/status/1046363142077513728

**Comment by sw-yx** [comment]
hye Scott! thank you. i will try this out now. sorry its taking me so long to get up to speed.

**Comment by spences10** [comment]
Couldn't get it to work with styled-components
